import type {
  Holding,
  HoldingDecision,
  MarketEvent,
  PortfolioSnapshot,
  ScenarioPreset,
  Transaction,
} from "@/lib/types";

const today = "2026-07-31";

export const sampleHoldings: Holding[] = [
  {
    id: "sample-msft",
    asset_type: "stock",
    ticker: "MSFT",
    isin: "US5949181045",
    figi: "BBG000BPH459",
    exchange: "NASDAQ",
    name: "Microsoft",
    quantity: 15,
    average_cost: 216.05,
    market_price: 466.67,
    currency: "USD",
    country: "United States",
    sector: "Technology",
    region: "North America",
    account_note: "Core compounder",
    manual_value_nok: 70000,
    factor_exposures: { globalEquity: 0.45, usEquity: 0.8, technology: 1, usdNok: 1 },
    issuer: null,
    coupon_rate: null,
    maturity_date: null,
    face_value: null,
    yield_estimate: null,
    duration_estimate: null,
    credit_quality: null,
    seniority: null,
    price_provenance: {
      source: "Manual NOK value",
      as_of: today,
      status: "manual",
      note: "Portfolio sleeve set to NOK 70,000; replace with a verified daily close when coverage is configured.",
    },
  },
  {
    id: "sample-googl",
    asset_type: "stock",
    ticker: "GOOGL",
    isin: "US02079K3059",
    figi: "BBG009S39JX6",
    exchange: "NASDAQ",
    name: "Alphabet",
    quantity: 20,
    average_cost: 210,
    market_price: 315,
    currency: "USD",
    country: "United States",
    sector: "Communication Services",
    region: "North America",
    account_note: "Bought near USD 210; search, ads, cloud, and AI infrastructure exposure",
    manual_value_nok: 45000,
    factor_exposures: { globalEquity: 0.45, usEquity: 0.8, technology: 0.6, usdNok: 1 },
    issuer: null,
    coupon_rate: null,
    maturity_date: null,
    face_value: null,
    yield_estimate: null,
    duration_estimate: null,
    credit_quality: null,
    seniority: null,
    price_provenance: {
      source: "Manual NOK value",
      as_of: today,
      status: "manual",
      note: "The stored NOK value overrides quantity × price.",
    },
  },
  {
    id: "sample-nvda",
    asset_type: "stock",
    ticker: "NVDA",
    isin: "US67066G1040",
    figi: "BBG000BBJQV0",
    exchange: "NASDAQ",
    name: "Nvidia",
    quantity: 30,
    average_cost: 61.73,
    market_price: 166.67,
    currency: "USD",
    country: "United States",
    sector: "Technology",
    region: "North America",
    account_note: "Focused AI compute and accelerated-data-centre exposure",
    manual_value_nok: 50000,
    factor_exposures: { globalEquity: 0.55, usEquity: 0.9, technology: 1.25, usdNok: 1 },
    issuer: null,
    coupon_rate: null,
    maturity_date: null,
    face_value: null,
    yield_estimate: null,
    duration_estimate: null,
    credit_quality: null,
    seniority: null,
    price_provenance: {
      source: "Manual NOK value",
      as_of: today,
      status: "manual",
      note: "Portfolio sleeve set to NOK 50,000; market price is illustrative until a daily provider is connected.",
    },
  },
  {
    id: "sample-sxr8",
    asset_type: "etf",
    ticker: "SXR8",
    isin: "IE00B5BMR087",
    figi: null,
    exchange: "XETRA",
    name: "iShares Core S&P 500 UCITS ETF",
    quantity: 30,
    average_cost: 360.14,
    market_price: 706.21,
    currency: "EUR",
    country: "Ireland",
    sector: "Diversified",
    region: "Europe",
    account_note: "Main S&P 500 ETF exposure from Nordnet",
    manual_value_nok: 285000,
    factor_exposures: { globalEquity: 0.75, usEquity: 1, europeEquity: 0.1, technology: 0.35, nokEur: 1 },
    issuer: null,
    coupon_rate: null,
    maturity_date: null,
    face_value: null,
    yield_estimate: null,
    duration_estimate: null,
    credit_quality: null,
    seniority: null,
    price_provenance: {
      source: "Manual NOK value",
      as_of: today,
      status: "manual",
      note: "Daily European ETF coverage is not yet connected.",
    },
  },
];

export const sampleTransactions: Transaction[] = [
  {
    id: "tx-deposit-2020",
    holding_id: null,
    type: "deposit",
    occurred_at: "2020-06-15",
    quantity: null,
    unit_price: null,
    amount: 227850,
    fee: 0,
    currency: "NOK",
    fx_to_nok: 1,
    split_ratio: null,
    note: "Opening capital represented by the legacy cost basis.",
  },
  {
    id: "tx-msft-opening",
    holding_id: "sample-msft",
    type: "opening_balance",
    occurred_at: "2020-06-15",
    quantity: 15,
    unit_price: 216.05,
    amount: null,
    fee: 0,
    currency: "USD",
    fx_to_nok: 10.8,
    split_ratio: null,
    note: "Legacy opening balance",
  },
  {
    id: "tx-googl-opening",
    holding_id: "sample-googl",
    type: "opening_balance",
    occurred_at: "2020-06-15",
    quantity: 20,
    unit_price: 210,
    amount: null,
    fee: 0,
    currency: "USD",
    fx_to_nok: 10.8,
    split_ratio: null,
    note: "Legacy opening balance",
  },
  {
    id: "tx-nvda-opening",
    holding_id: "sample-nvda",
    type: "opening_balance",
    occurred_at: "2020-06-15",
    quantity: 30,
    unit_price: 61.73,
    amount: null,
    fee: 0,
    currency: "USD",
    fx_to_nok: 10.8,
    split_ratio: null,
    note: "Legacy opening balance",
  },
  {
    id: "tx-sxr8-opening",
    holding_id: "sample-sxr8",
    type: "opening_balance",
    occurred_at: "2020-06-15",
    quantity: 30,
    unit_price: 360.14,
    amount: null,
    fee: 0,
    currency: "EUR",
    fx_to_nok: 11.8,
    split_ratio: null,
    note: "Legacy opening balance",
  },
];

export const sampleSnapshots: PortfolioSnapshot[] = [
  { id: "snap-2020", snapshot_date: "2020-06-15", total_value_nok: 227850, external_flow_nok: 227850, source: "legacy_estimate" },
  { id: "snap-2021", snapshot_date: "2021-12-31", total_value_nok: 286400, external_flow_nok: 0, source: "legacy_estimate" },
  { id: "snap-2022", snapshot_date: "2022-12-31", total_value_nok: 251900, external_flow_nok: 0, source: "legacy_estimate" },
  { id: "snap-2023", snapshot_date: "2023-12-31", total_value_nok: 326800, external_flow_nok: 0, source: "legacy_estimate" },
  { id: "snap-2024", snapshot_date: "2024-12-31", total_value_nok: 382100, external_flow_nok: 0, source: "legacy_estimate" },
  { id: "snap-2025", snapshot_date: "2025-12-31", total_value_nok: 421500, external_flow_nok: 0, source: "legacy_estimate" },
  { id: "snap-today", snapshot_date: today, total_value_nok: 450000, external_flow_nok: 0, source: "legacy_estimate" },
];

export const sampleDecisions: HoldingDecision[] = [
  {
    id: "decision-msft",
    holding_id: "sample-msft",
    status: "hold",
    thesis: "Enterprise distribution, Azure scale, and recurring software revenue can support long-term compounding.",
    reason_for_ownership: "A durable business I understand and intend to hold through ordinary volatility.",
    return_drivers: "Azure growth, Copilot monetization, operating leverage, and capital returns.",
    risks: "Valuation compression, cloud competition, rising AI capital intensity, and regulation.",
    conviction: 5,
    review_date: "2026-10-30",
    note: "Review after the next two earnings reports rather than reacting to a single price move.",
    recorded_at: "2026-07-30T08:00:00.000Z",
  },
  {
    id: "decision-googl",
    holding_id: "sample-googl",
    status: "hold",
    thesis: "Search economics, YouTube, Cloud, and AI infrastructure provide several independent growth engines.",
    reason_for_ownership: "A familiar, cash-generative platform with room for cloud margin expansion.",
    return_drivers: "Search monetization, YouTube growth, Google Cloud margins, and AI adoption.",
    risks: "AI search disruption, regulation, ad cyclicality, and capital spending.",
    conviction: 4,
    review_date: "2026-10-30",
    note: null,
    recorded_at: "2026-07-30T08:05:00.000Z",
  },
  {
    id: "decision-nvda",
    holding_id: "sample-nvda",
    status: "hold",
    thesis: "Accelerated computing can remain a critical layer of AI infrastructure, supported by a broad software and networking ecosystem.",
    reason_for_ownership: "Focused exposure to AI compute alongside broader index ownership.",
    return_drivers: "Data-centre demand, product cadence, networking growth, and software adoption.",
    risks: "Customer concentration, export controls, competition, cyclicality, and valuation compression.",
    conviction: 4,
    review_date: "2026-10-30",
    note: "Track overlap with the S&P 500 ETF before increasing the direct position.",
    recorded_at: "2026-07-30T08:08:00.000Z",
  },
  {
    id: "decision-sxr8",
    holding_id: "sample-sxr8",
    status: "hold",
    thesis: "Broad US exposure remains the portfolio's diversified compounding engine.",
    reason_for_ownership: "Simple accumulating exposure reduces the need to continually select individual winners.",
    return_drivers: "US earnings growth, productivity, buybacks, and currency effects.",
    risks: "Index concentration, high valuation, and USD/NOK or EUR/NOK moves.",
    conviction: 5,
    review_date: "2026-11-15",
    note: "Monitor total US exposure across both the ETF and individual holdings.",
    recorded_at: "2026-07-30T08:10:00.000Z",
  },
];

export const sampleEvents: MarketEvent[] = [
  {
    id: "event-msft-review",
    holding_id: "sample-msft",
    title: "Microsoft thesis review",
    event_type: "review",
    event_date: "2026-10-30",
    source: "Decision Memory",
    source_url: null,
    status: "upcoming",
  },
  {
    id: "event-us-macro",
    holding_id: null,
    title: "US inflation and rates remain key portfolio factors",
    event_type: "macro",
    event_date: today,
    source: "FRED",
    source_url: "https://fred.stlouisfed.org/",
    status: "new",
  },
  {
    id: "event-europe-macro",
    holding_id: null,
    title: "European rates and industrial activity remain part of the daily cross-check",
    event_type: "macro",
    event_date: today,
    source: "ECB Data Portal",
    source_url: "https://data.ecb.europa.eu/",
    status: "new",
  },
  {
    id: "event-us-filings",
    holding_id: null,
    title: "US company filings should be checked against the technology concentration",
    event_type: "filing",
    event_date: today,
    source: "SEC EDGAR",
    source_url: "https://www.sec.gov/search-filings",
    status: "new",
  },
];

const blank = {
  globalEquity: 0,
  usEquity: 0,
  europeEquity: 0,
  technology: 0,
  industrials: 0,
  defense: 0,
  usdNok: 0,
  nokEur: 0,
  rates: 0,
  credit: 0,
  cash: 0,
};

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: "risk-off",
    name: "Global Risk-Off",
    description: "Broad equity decline, wider spreads, and a stronger US dollar.",
    shocks: { ...blank, globalEquity: -15, usEquity: -12, europeEquity: -18, technology: -20, usdNok: 7, rates: -50, credit: 150 },
  },
  {
    id: "recession",
    name: "US Recession",
    description: "Earnings contract, cyclicals weaken, spreads widen, and rates fall.",
    shocks: { ...blank, globalEquity: -12, usEquity: -18, technology: -12, industrials: -22, defense: -5, usdNok: 5, rates: -125, credit: 180 },
  },
  {
    id: "stagflation",
    name: "Stagflation",
    description: "Growth slows while inflation keeps rates and input costs elevated.",
    shocks: { ...blank, globalEquity: -12, usEquity: -15, europeEquity: -18, technology: -18, industrials: -10, defense: 3, usdNok: 6, rates: 125, credit: 100 },
  },
  {
    id: "rates-up",
    name: "Rates +100 bps",
    description: "Higher discount rates and refinancing costs pressure long-duration and indebted companies.",
    shocks: { ...blank, globalEquity: -3, usEquity: -6, technology: -11, industrials: -3, usdNok: 3, rates: 100, credit: 40 },
  },
  {
    id: "rates-down",
    name: "Rates -100 bps",
    description: "An orderly easing cycle supports duration-sensitive assets without a recession.",
    shocks: { ...blank, globalEquity: 3, usEquity: 6, technology: 9, industrials: 4, usdNok: -3, rates: -100, credit: -30 },
  },
  {
    id: "credit-wide",
    name: "Refinancing Wall",
    description: "Corporate spreads widen as lenders demand more compensation from leveraged borrowers.",
    shocks: { ...blank, globalEquity: -5, usEquity: -8, industrials: -9, technology: -4, usdNok: 4, credit: 150 },
  },
  {
    id: "ai-bubble",
    name: "AI Bubble Bursts",
    description: "AI-linked valuation multiples compress and hyperscaler capital spending is questioned.",
    shocks: { ...blank, globalEquity: -5, usEquity: -10, technology: -32, industrials: -5, usdNok: 2 },
  },
  {
    id: "ai-capex",
    name: "AI Capex Slowdown",
    description: "Cloud platforms slow data-centre investment without a broad economic recession.",
    shocks: { ...blank, globalEquity: -2, usEquity: -5, technology: -18, industrials: -7, usdNok: 1 },
  },
  {
    id: "mega-cap-rotation",
    name: "Mega-cap Rotation",
    description: "Market leadership broadens while richly valued technology leaders lag the equal-weight index.",
    shocks: { ...blank, globalEquity: 2, usEquity: 3, technology: -15, industrials: 8, defense: 5 },
  },
  {
    id: "oil-shock",
    name: "Oil Supply Shock",
    description: "Energy prices jump, inflation expectations rise, and margins compress outside energy.",
    shocks: { ...blank, globalEquity: -5, usEquity: -7, europeEquity: -9, technology: -6, industrials: -10, defense: 5, usdNok: 5, rates: 50, credit: 60 },
  },
  {
    id: "nok-strengthens",
    name: "NOK Strengthening",
    description: "NOK appreciates against USD and EUR while local assets are unchanged.",
    shocks: { ...blank, usdNok: -10, nokEur: -8 },
  },
  {
    id: "custom",
    name: "Blank Custom",
    description: "Start from a neutral scenario and set each factor directly.",
    shocks: { ...blank },
  },
];
